export interface Item{

	applicable_tax:'DEFAULT'|'EXEMPT'|'PERCENT';
	availability_type:'ON_STOCK'|'BY_ORDER'|'ALWAYS';
	commission_type:'NONE'|'AMOUNT'|'PERCENT';
	for_reservation:'YES'|'NO';
	has_serial_number:'NO'|'YES';
	ieps_type:'RATE'|'AMOUNT';
	image_style:'COVER'|'CONTAIN';
	note_required:'NO'|'YES';
	on_sale:'NO'|'YES';
	partial_sale:'NO'|'YES';
	period_type:'BY_HOUR'|'DAILY'|'WEEKLY'|'MONTHLY';
	response_requirement_qty:'ONCE_PER_CLIENT'|'ONCE_PER_SALE'|'EVERY_ITEM';
	return_action:'RETURN_TO_STOCK'|'ADD_TO_MERMA'|'TRANSFORM_INTO_ITEM';
	status:'ACTIVE'|'DELETED';
	stock_type:'NORMAL'|'BATCH';
	text_style:'NEVER'|'CENTER'|'DOWN';
  background:string;
  brand_id:number | null;
  category_id:number | null;
  clave_sat:string | null;
  code:string | null;
  commanda_type_id:number | null;
  commission:number;
  commission_currency_id:string;
  created:string;
  created_by_user_id:number | null;
  currency_id:string;
  description:string | null;
  extra_name:string | null;
  form_id:number | null;
  id:number;
  ieps_value:number;
  image_id:number | null;
  json_tags:any;
  measurement_unit:string | null;
  name:string;
  product_id:number | null;
  provider_user_id:number | null;
  reference_currency_id:string;
  reference_price:number;
  shadow_color:string;
  sort_weight:number;
  tax_percent:number;
  text_color:string;
  unidad_medida_sat_id:string;
  updated:string;
  updated_by_user_id:number | null;
}