export interface Order{

	delivery_status:'PENDING'|'SENT'|'DELIVERED'|'CANCELLED'|'READY_TO_PICKUP';
	facturado:'NO'|'YES';
	frequency:'WEEKLY'|'MONTHLY'|'2X_MONTHLY'|'NONE';
	marked_for_billing:'YES'|'NO';
	paid_status:'PENDING'|'PAID'|'PARTIALLY_PAID';
	service_type:'TOGO'|'IN_PLACE'|'PICK_UP'|'QUICK_SALE';
	status:'PENDING'|'CANCELLED'|'ACTIVE'|'CLOSED'|'PENDING_PAUSED';
  address:string | null;
  amount_paid:number;
  ares:number;
  authorized_by:string | null;
  billing_address_id:number | null;
  billing_data_id:number | null;
  cancellation_reason:string | null;
  cancellation_timestamp:string | null;
  cancelled_by_user_id:number | null;
  cashier_user_id:number | null;
  city:string | null;
  client_name:string | null;
  client_user_id:number | null;
  closed_by_user_id:number | null;
  closed_timestamp:string | null;
  created:string;
  currency_id:string;
  delivery_schedule:string | null;
  delivery_user_id:number | null;
  discount:number;
  discount_calculated:number;
  ecommerce_user_id:number | null;
  external_id:string | null;
  facturacion_code:string;
  facturacion_timestamp:string | null;
  first_payment_date:string | null;
  guests:number;
  id:number;
  initial_payment:number;
  installment_amount:number | null;
  installment_months:number | null;
  installment_round_amount:number;
  installments:number | null;
  lat:number | null;
  lng:number | null;
  note:string | null;
  paid_timetamp:string | null;
  period_id:number | null;
  price_type_id:number;
  quote_id:number | null;
  sat_codigo_postal:string | null;
  sat_domicilio_fiscal_receptor:string;
  sat_exchange_rate:number;
  sat_factura_id:number | null;
  sat_forma_pago:string;
  sat_ieps:number;
  sat_isr:number;
  sat_pdf_attachment_id:number | null;
  sat_razon_social:string | null;
  sat_receptor_email:string | null;
  sat_receptor_rfc:string | null;
  sat_regimen_capital_receptor:string;
  sat_regimen_fiscal_receptor:string;
  sat_serie:string | null;
  sat_serie_consecutive:number | null;
  sat_uso_cfdi:string | null;
  sat_xml_attachment_id:number | null;
  shipping_address_id:number | null;
  shipping_cost:number;
  state:string | null;
  store_consecutive:number;
  store_id:number;
  subtotal:number;
  suburb:string | null;
  sync_id:string | null;
  system_activated:string | null;
  table_id:number | null;
  tag:string | null;
  tax:number;
  tax_percent:number;
  total:number;
  updated:string;
  version_created:string;
  version_updated:string;
}