export interface Store{

	accept_delivery_orders:'NEVER'|'ONLY_PREPAID'|'ALWAYS';
	accept_pickup_orders:'NEVER'|'ONLY_PREPAID'|'ALWAYS';
	autofacturacion_enabled:'YES'|'NO';
	autofacturacion_settings:'ONLY_SAME_MONTH'|'ONLY_DAY_LIMIT'|'BOTH'|'DISABLED';
	modo_facturacion:'DESGLOSADA'|'COMPACTA';
	pos_category_preferences:'DEFAULT_BY_PRODUCT'|'HIDE_BY_DEFAULT'|'SHOW_BY_DEFAULT';
	print_mode:'REDIRECT'|'NEW_WINDOW'|'POPUP';
	qr_size:'PERCENT_25'|'PERCENT_50'|'PERCENT_75'|'PERCENT_100';
	show_facturacion_qr:'NO'|'YES';
	status:'ACTIVE'|'DISABLED';
	ticket_address_display:'SUCURSAL'|'DIRECCION_FISCAL';
  accept_cash:number;
  accept_check:number;
  accept_credit_card:number;
  accept_transfer:number;
  address:string | null;
  autofacturacion_day_limit:number;
  business_name:string | null;
  city:string | null;
  client_user_id:number | null;
  code:string | null;
  created:string;
  created_by_user_id:number | null;
  default_billing_data_id:number | null;
  default_claveprodserv:string | null;
  default_currency_id:string;
  default_sat_item_name:string;
  default_sat_serie:string;
  electronic_transfer_percent_fee:number;
  exchange_rate:number;
  id:number;
  image_id:number | null;
  lat:number | null;
  lng:number | null;
  main_pc_ip:string | null;
  max_cash_amount:number;
  name:string;
  offline_search_enabled:number;
  paypal_email:string | null;
  phone:string | null;
  price_list_id:number | null;
  print_delay:number;
  print_receipt:number | null;
  print_receipt_copies:number;
  printer_ticket_config:string | null;
  production_enabled:number;
  rfc:string | null;
  sales_enabled:number;
  state:string | null;
  suggested_tip:number;
  tax_percent:number;
  ticket_footer_text:string | null;
  ticket_image_id:number | null;
  updated:string;
  updated_by_user_id:number | null;
  zipcode:string | null;
}